### ISSUE TITLE
Enable round robin on targets

### ISSUE THREAD

**Issue by jackmaresca** [Roslovets-Inc/greenlock-proxy#3]
Hello, thanks for this nice little proxy.
Would it be possible to add round robin targets...maybe passing an array of targets?
Like:

proxy.register(["www.dev.example.com"], ["http://192.168.1.20:3000","http://192.168.1.21:3000","http://192.168.1.22:3000"]);

**Comment by roslovets** [comment]
Hi, thanks. I'll see what I can do.

**Comment by roslovets** [comment]
@jackmaresca check out the latest version. I've added simple random balancer according to your suggestion.
Adding round robin is quite tricky, you can help with that if you like :)

**Comment by jackmaresca** [comment]
:+1:   Good !!! An alternative to avoid computing Math functions would be a global round robin with a global variable and increment just before forwarding: 

           this.rr++;
           this.rr  = this.rr % target.length; //round robin on target arrays
           proxy.web(req, res, {
           target: target[this.rr]

Choose the best and this issue can be close..thank you! 
If you like I can contribute in the spare time because other features could be added (like passing proxy parameters, checking if targets are offline ..and so on)

**Comment by roslovets** [comment]
> An alternative to avoid computing Math functions would be a global round robin with a global variable and increment just before forwarding

One problem I see here: if you register several domains they will share the same global variable. Seems like every registered domain needs its own incrementable variable.

> If you like I can contribute in the spare time because other features could be added

It would be definitely cool!

**Comment by jackmaresca** [comment]
> One problem I see here: if you register several domains they will share the same global variable. Seems like every registered domain needs its own incrementable variable.

Thats true..so we can close this for now ..I'll push PR when i have time to see if we can add features even if I am the worst programmer in the world ahaha..for now thank you
